version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Отключаем авторизацию для простоты
    ports:
      - "9200:9200"
    networks:
      - es_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.0
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - es_network
    depends_on:
      - elasticsearch

networks:
  es_network:
    driver: bridge
